core:
  build: .
  env_file:
   - ./docker-dspace/conf/database.conf
   - ./docker-dspace/conf/dspace.conf
   - ./build.properties
data:
  extends: 
    file: ./docker-dspace/docker-compose.yml
    service: data
dev:
  extends: 
    file: ./docker-dspace/docker-compose.yml
    service: dev
prepare_dev:
  extends: 
    file: ./docker-dspace/docker-compose.yml
    service: prepare_dev
prepare_dev:
  extends: 
    file: ./docker-dspace/docker-compose.yml
    service: prepare_dev

